Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [16]:
import numpy as np
n=3
arr=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
def movavg(ar,n):
    ma=np.cumsum(np.insert(ar,0,0))
    return (ma[n:] - ma[:-n])/ float(n)
movavg(arr,n)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [29]:
arr=np.array([2,4,6,8])
def van(arr,y):
    print(np.array(np.vander(arr,y)))
van(arr,5)

[[  16    8    4    2    1]
 [ 256   64   16    4    1]
 [1296  216   36    6    1]
 [4096  512   64    8    1]]
